### ISSUE TITLE
Problem in pubmed parser with abstract

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#222]
```
<11>Spider error processing <GET http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi/?db=pubmed&id=23586654&retmode=xml> (referer: None) 
Traceback (most recent call last):   
File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks     current.result = callback(current.result, *args, **kw)   
File "collectors/pubmed/parser.py", line 75, in parse_record     text.append(subelem['#text']) KeyError: u'#text' 
```

affecting around 2-3 records from 1000

**Comment by vitorbaptista** [comment]
Closing this as it's too old and it might not be valid anymore. We now have Sentry on our data pipeline, so we'll be notified if this happen again and we can reopen it.
