### ISSUE TITLE
Problem in hra parser with defered data

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#224]
1-2 cases per 1000

```
Parsing error: decision_date=Publication of this data is currently deferred.: time data 'Publication of this data is currently deferred.' does not match format '%Y-%m-%d %H:%M:%S' 
Traceback (most recent call last):   
File "collectors/base/record.py", line 78, in create     value = field.parse(value)   
File "collectors/base/fields.py", line 98, in parse     value = helpers.parse_datetime(value, format=self.__format)   
File "collectors/base/helpers.py", line 35, in parse_datetime     return datetime.datetime.strptime(value, format)   
File "/usr/local/lib/python2.7/_strptime.py", line 325, in _strptime     (data_string, format)) 
ValueError: time data 'Publication of this data is currently deferred.' does not match format '%Y-%m-%d %H:%M:%S' 
```

**Comment by vitorbaptista** [comment]
Closing this as it's too old and it might not be valid anymore. We now have Sentry on our data pipeline, so we'll be notified if this happen again and we can reopen it.
