### ISSUE TITLE
Problem in hra processor with isrctn id

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#225]
1-2 cases per 100

```
Processing error: TypeError('expected string or buffer',) [8] Traceback (most recent call last):   
File "processors/base/processors/trial.py", line 38, in process_trial     trial = extractors['extract_trial'](record)   
File "processors/hra/extractors.py", line 27, in extract_trial     'isrctn': _clean_identifier(record['isrctn_id'], prefix='ISRCTN'),   
File "processors/hra/extractors.py", line 93, in _clean_identifier     if re.match(r'%s\d{3,}' % prefix, ident):   File "/usr/local/lib/python2.7/re.py", line 141, in match     return _compile(pattern, flags).match(string) 
TypeError: expected string or buffer 
```

**Comment by vitorbaptista** [comment]
Closing this as it's too old and it might not be valid anymore. We now have Sentry on our data pipeline, so we'll be notified if this happen again and we can reopen it.
