### ISSUE TITLE
Migrations rollback fails because of unique constraint

### ISSUE THREAD

**Issue by georgiana-b** [opentrials/opentrials#422]
After running `npm run migrate` on a newly created database, `knex migrate:rollback` fails with this error:

```
Knex:warning - migrations failed with error: alter table "documents" drop constraint "documents_trial_id_fda_approval_id_url_unique" - constraint "documents_trial_id_fda_approval_id_url_unique" of relation "documents" does not exist
error: alter table "documents" drop constraint "documents_trial_id_fda_approval_id_url_unique" - constraint "documents_trial_id_fda_approval_id_url_unique" of relation "documents" does not exist
    at Connection.parseE (/home/g/Documents/opentrials-api/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/home/g/Documents/opentrials-api/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/home/g/Documents/opentrials-api/node_modules/pg/lib/connection.js:117:22)
```

**Comment by vitorbaptista** [comment]
Couldn't reproduce
