### ISSUE TITLE
Reindexing throws "illegal_argument_exception" and deletes old indexes even on error

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#693]
The traceback we get is:

```
346210 entities being indexed in "trials_2017-02-23_1487871197988/trial" (1000 at a time).
{ Error: [illegal_argument_exception] Malformed action/metadata line [153], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]
    at respond (/app/node_modules/elasticsearch/src/lib/transport.js:289:15)
    at checkRespForFailure (/app/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpAmazonESConnector.<anonymous> (/app/node_modules/http-aws-es/connector.js:86:11)
    at IncomingMessage.wrapper (/app/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  status: 400,
  displayName: 'BadRequest',
  message: '[illegal_argument_exception] Malformed action/metadata line [153], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]',
  path: '/_bulk',
  query: {},
  body: 
   { error: 
      { root_cause: [Object],
        type: 'illegal_argument_exception',
        reason: 'Malformed action/metadata line [153], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]' },
     status: 400 },
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Malformed action/metadata line [153], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]"}],"type":"illegal_argument_exception","reason":"Malformed action/metadata line [153], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]"},"status":400}',
  toString: [Function],
  toJSON: [Function] }
Removing old indexes: trials_2017-01-31_1485889385140
```

This shows not only the exception, but also that it deleted the old index even though the new index failed.

**Comment by vitorbaptista** [comment]
All went fine for the `trials` and `autocomplete` indexes, but the same is still happening with `fdaDocuments`

**Comment by vitorbaptista** [comment]
This error was caused by a bug on NodeJS (https://github.com/nodejs/node/issues/11545). I merged a workaround on https://github.com/opentrials/api/issues/149, so all's good.
